import React, { useState, useRef } from 'react';
import { parseVehicleCsv, parseDriverCsv } from '../../lib/csvParser';
import { bulkUploadVehicles, bulkUploadDrivers, clearAllFleetData, clearAllVehicles, clearAllDrivers } from '../../lib/api';
import { Vehicle, Driver } from '../../types';
import { Upload, Download, FileText, CheckCircle2, AlertTriangle, RefreshCw, Truck, Users, QrCode, ArrowRight, Printer, Trash2, ShieldAlert, Sparkles, X } from 'lucide-react';
import QRCodeLib from 'qrcode';
import { buildVehicleDeepLink } from '../../lib/publicUrl';

export const BulkManager: React.FC = () => {
  const [activeType, setActiveType] = useState<'vehicles' | 'drivers'>('vehicles');
  const [csvContent, setCsvContent] = useState<string>('');
  const [parsedVehicles, setParsedVehicles] = useState<Partial<Vehicle>[]>([]);
  const [parsedDrivers, setParsedDrivers] = useState<Partial<Driver>[]>([]);
  const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [autoGeneratedQrs, setAutoGeneratedQrs] = useState<Array<{ plate: string; brand: string; model: string; qrUrl: string }>>([]);
  const [showWipeModal, setShowWipeModal] = useState<boolean>(false);
  const [wipeMode, setWipeMode] = useState<'all' | 'vehicles' | 'drivers'>('all');
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result as string;
      setCsvContent(text);
      parseInput(text, activeType);
    };
    reader.readAsText(file);
  };

  const handleTextChange = (text: string) => {
    setCsvContent(text);
    parseInput(text, activeType);
  };

  const parseInput = (text: string, type: 'vehicles' | 'drivers') => {
    setStatusMsg(null);
    if (!text.trim()) {
      setParsedVehicles([]);
      setParsedDrivers([]);
      return;
    }

    if (type === 'vehicles') {
      const list = parseVehicleCsv(text);
      setParsedVehicles(list);
      if (list.length === 0) {
        setStatusMsg({ type: 'error', text: 'No valid vehicle records found. Please ensure headers match template.' });
      }
    } else {
      const list = parseDriverCsv(text);
      setParsedDrivers(list);
      if (list.length === 0) {
        setStatusMsg({ type: 'error', text: 'No valid driver records found. Please ensure headers match template.' });
      }
    }
  };

  const handleTypeSwitch = (type: 'vehicles' | 'drivers') => {
    setActiveType(type);
    setCsvContent('');
    setParsedVehicles([]);
    setParsedDrivers([]);
    setStatusMsg(null);
    setAutoGeneratedQrs([]);
  };

  const handleCommit = async () => {
    setIsProcessing(true);
    setStatusMsg(null);
    try {
      if (activeType === 'vehicles') {
        if (parsedVehicles.length === 0) {
          setStatusMsg({ type: 'error', text: 'No vehicle rows to commit.' });
          return;
        }
        const res = await bulkUploadVehicles(parsedVehicles);
        if (res.success) {
          setStatusMsg({
            type: 'success',
            text: `Successfully updated ${res.updated} and added ${res.added} vehicles. QR Codes generated automatically!`,
          });

          // Auto-generate QR codes for the uploaded vehicles
          const qrs = await Promise.all(
            parsedVehicles.slice(0, 30).map(async (v) => {
              const plate = (v.vehicleNo || '').toUpperCase();
              const inspectionUrl = buildVehicleDeepLink(plate, undefined, v.qrToken);
              const qrUrl = await QRCodeLib.toDataURL(inspectionUrl, {
                width: 160,
                margin: 1,
                color: { dark: '#0F172A', light: '#FFFFFF' },
              });
              return {
                plate,
                brand: v.brand || 'Commercial',
                model: v.model || 'Vehicle',
                qrUrl,
              };
            })
          );
          setAutoGeneratedQrs(qrs);

          setCsvContent('');
          setParsedVehicles([]);
        } else {
          setStatusMsg({ type: 'error', text: res.message || 'Bulk upload failed.' });
        }
      } else {
        if (parsedDrivers.length === 0) {
          setStatusMsg({ type: 'error', text: 'No driver rows to commit.' });
          return;
        }
        const res = await bulkUploadDrivers(parsedDrivers);
        if (res.success) {
          setStatusMsg({ type: 'success', text: `Successfully updated ${res.updated} and added ${res.added} driver profiles.` });
          setCsvContent('');
          setParsedDrivers([]);
        } else {
          setStatusMsg({ type: 'error', text: res.message || 'Bulk upload failed.' });
        }
      }
    } catch (err: any) {
      setStatusMsg({ type: 'error', text: err.message || 'Connection error during bulk synchronization.' });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleExecuteWipe = async () => {
    setIsProcessing(true);
    setStatusMsg(null);
    try {
      if (wipeMode === 'all') {
        const res = await clearAllFleetData();
        setStatusMsg({
          type: 'success',
          text: res.message || 'All fleet data wiped. The system is completely clean.',
        });
      } else if (wipeMode === 'vehicles') {
        const res = await clearAllVehicles();
        setStatusMsg({
          type: 'success',
          text: res.message || 'All vehicles cleared from database.',
        });
      } else if (wipeMode === 'drivers') {
        const res = await clearAllDrivers();
        setStatusMsg({
          type: 'success',
          text: res.message || 'All drivers cleared from database.',
        });
      }
      setCsvContent('');
      setParsedVehicles([]);
      setParsedDrivers([]);
      setAutoGeneratedQrs([]);
      setShowWipeModal(false);
    } catch (err: any) {
      setStatusMsg({ type: 'error', text: err.message || 'Failed to clear data.' });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Zero-Preset Notice & Database Management Header */}
      <div className="bg-gradient-to-r from-slate-900 to-slate-800 text-white rounded-2xl p-5 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center space-x-3.5">
          <div className="w-10 h-10 rounded-xl bg-blue-600/20 border border-blue-500/30 flex items-center justify-center text-blue-400 flex-shrink-0">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <span className="font-bold text-sm text-white">Custom Upload Mode Active</span>
              <span className="text-[10px] font-bold uppercase bg-emerald-500/20 border border-emerald-400/40 text-emerald-300 px-2 py-0.5 rounded-full">
                Zero Presets
              </span>
            </div>
            <p className="text-xs text-slate-300">
              No preset/dummy data is loaded. Use the CSV uploader below to import your own fleet vehicles and drivers.
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            type="button"
            onClick={() => {
              setWipeMode('all');
              setShowWipeModal(true);
            }}
            className="bg-rose-500/10 hover:bg-rose-500/20 border border-rose-400/40 text-rose-300 hover:text-rose-200 text-xs font-bold px-3.5 py-2 rounded-xl flex items-center space-x-1.5 transition cursor-pointer"
          >
            <Trash2 className="w-4 h-4 text-rose-400" />
            <span>Wipe / Reset Database</span>
          </button>
        </div>
      </div>

      {/* Top Header & Type Switcher */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm text-slate-800">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-lg font-bold tracking-tight text-slate-900">Bulk Data Upload & Auto QR Generation</h2>
            <p className="text-xs text-slate-500">Upload fleet inventory and drivers. System automatically generates QR labels for drivers to scan.</p>
          </div>

          {/* Type Toggle Tabs */}
          <div className="flex items-center p-1 bg-slate-100 rounded-xl border border-slate-200 self-start sm:self-auto">
            <button
              onClick={() => handleTypeSwitch('vehicles')}
              className={`flex items-center space-x-2 px-4 py-2 rounded-lg text-xs font-bold transition cursor-pointer ${
                activeType === 'vehicles' ? 'bg-blue-600 text-white shadow-sm shadow-blue-500/30' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Truck className="w-4 h-4" />
              <span>Vehicles & QR Auto-Gen</span>
            </button>
            <button
              onClick={() => handleTypeSwitch('drivers')}
              className={`flex items-center space-x-2 px-4 py-2 rounded-lg text-xs font-bold transition cursor-pointer ${
                activeType === 'drivers' ? 'bg-blue-600 text-white shadow-sm shadow-blue-500/30' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Users className="w-4 h-4" />
              <span>Drivers Directory</span>
            </button>
          </div>
        </div>

        {/* Template Downloader Box */}
        <div className="mt-5 p-4 bg-slate-50 rounded-xl border border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center space-x-3">
            <FileText className="w-8 h-8 text-blue-600 flex-shrink-0" />
            <div className="text-xs">
              <span className="font-bold text-slate-900 block">
                Standard {activeType === 'vehicles' ? 'Vehicle Fleet' : 'Driver Roster'} CSV Template
              </span>
              <span className="text-slate-500">
                Download the standardized CSV format, fill in records in Excel, and upload here.
              </span>
            </div>
          </div>

          <a
            href={activeType === 'vehicles' ? '/api/templates/vehicles.csv' : '/api/templates/drivers.csv'}
            download
            className="bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 text-xs font-bold px-4 py-2.5 rounded-xl flex items-center justify-center space-x-2 transition flex-shrink-0 shadow-sm cursor-pointer"
          >
            <Download className="w-4 h-4 text-blue-600" />
            <span>Download {activeType === 'vehicles' ? 'Vehicle' : 'Driver'} Template (.CSV)</span>
          </a>
        </div>
      </div>

      {/* Auto Generated QR Codes Banner (if any recently created) */}
      {autoGeneratedQrs.length > 0 && (
        <div className="bg-white border border-blue-200 rounded-2xl p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2.5">
              <div className="w-9 h-9 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600">
                <QrCode className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-sm text-slate-900">
                  Auto-Generated QR Decal Codes ({autoGeneratedQrs.length} Vehicles)
                </h3>
                <p className="text-xs text-slate-500">Drivers scan these vehicle QR codes to start their 10-point daily inspection directly.</p>
              </div>
            </div>

            <button
              onClick={() => window.print()}
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs px-3.5 py-2 rounded-xl flex items-center space-x-1.5 shadow-sm transition cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>Print All QR Stickers</span>
            </button>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
            {autoGeneratedQrs.map((item, idx) => (
              <div key={idx} className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center space-y-2">
                <div className="font-mono font-bold text-xs text-slate-900">{item.plate}</div>
                <img src={item.qrUrl} alt={item.plate} className="w-24 h-24 mx-auto bg-white p-1 rounded-lg border border-slate-200 shadow-sm" />
                <div className="text-[10px] text-slate-500 truncate">{item.brand} {item.model}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Upload or Paste Form */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm text-slate-800 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <h3 className="font-bold text-sm text-slate-900">
            Paste CSV Records or Select File
          </h3>
          
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 text-xs font-semibold px-3.5 py-2 rounded-xl flex items-center space-x-1.5 transition self-start sm:self-auto cursor-pointer shadow-sm"
          >
            <Upload className="w-4 h-4 text-blue-600" />
            <span>Select Local .CSV File</span>
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept=".csv,text/csv,text/plain"
            onChange={handleFileUpload}
            className="hidden"
          />
        </div>

        <textarea
          rows={6}
          value={csvContent}
          onChange={(e) => handleTextChange(e.target.value)}
          placeholder={
            activeType === 'vehicles'
              ? 'No,Card No,Vehicle No,PIN No,Litre,Limit RM,Area,Branch,Cost Center,Brand,Model,Year,Tonnage,Capacity,Tyre Size,Battery Type,Permit\n1,7002841-710588-019972,VFH2715,3052,24,107,LOG-B,KL,K11200,HINO,XZU600R-HKMLJ3,2020,1,4009,205/85R x 16,NS70L = 2,JPJ'
              : 'No,Depot,Depot Name,Employee ID,Login ID,Password,Name,Designation,License Type,Phone,Status\n1,BL,BALAKONG,SF7620,7620,762001,AZIMUL AMRI BIN CHE SHA\'ARI,SALESMAN,GDL / Class E Heavy,+60 12-384 7620,A'
          }
          className="w-full bg-slate-50 border border-slate-300 rounded-xl p-3.5 text-xs text-slate-900 font-mono placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-sm"
        />

        {statusMsg && (
          <div
            className={`p-3.5 rounded-xl border text-xs font-semibold flex items-center space-x-2 ${
              statusMsg.type === 'success'
                ? 'bg-emerald-50 border-emerald-200 text-emerald-800'
                : 'bg-rose-50 border-rose-200 text-rose-800'
            }`}
          >
            {statusMsg.type === 'success' ? <CheckCircle2 className="w-4 h-4 text-emerald-600" /> : <AlertTriangle className="w-4 h-4 text-rose-600" />}
            <span>{statusMsg.text}</span>
          </div>
        )}

        {/* Live Preview Table */}
        {activeType === 'vehicles' && parsedVehicles.length > 0 && (
          <div className="space-y-2 pt-2">
            <div className="flex items-center justify-between text-xs text-slate-700 font-medium">
              <span>Previewing <strong className="text-blue-600">{parsedVehicles.length}</strong> vehicle records to be synchronized and assigned QR codes:</span>
            </div>
            <div className="overflow-x-auto max-h-60 rounded-xl border border-slate-200">
              <table className="w-full text-left text-xs text-slate-700">
                <thead className="bg-slate-50 text-slate-500 text-[10px] uppercase font-bold border-b border-slate-200">
                  <tr>
                    <th className="px-3 py-2">Plate</th>
                    <th className="px-3 py-2">Branch / Depot</th>
                    <th className="px-3 py-2">Brand & Model</th>
                    <th className="px-3 py-2">Card No</th>
                    <th className="px-3 py-2">PIN</th>
                    <th className="px-3 py-2">Tonnage</th>
                    <th className="px-3 py-2">Tyres</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 bg-white font-mono text-[11px]">
                  {parsedVehicles.slice(0, 15).map((v, idx) => (
                    <tr key={idx} className="hover:bg-slate-50">
                      <td className="px-3 py-1.5 font-bold text-slate-900">{v.vehicleNo}</td>
                      <td className="px-3 py-1.5">
                        <span className="bg-slate-100 px-1.5 py-0.5 rounded font-bold text-slate-700 text-[10px]">
                          {v.branch}
                        </span>
                      </td>
                      <td className="px-3 py-1.5 font-sans font-semibold text-slate-800">{v.brand} {v.model}</td>
                      <td className="px-3 py-1.5 text-slate-600">{v.cardNo}</td>
                      <td className="px-3 py-1.5 text-slate-700">{v.pinNo}</td>
                      <td className="px-3 py-1.5 font-sans text-slate-700">{v.tonnage}T</td>
                      <td className="px-3 py-1.5 text-slate-500">{v.tyreSize}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {activeType === 'drivers' && parsedDrivers.length > 0 && (
          <div className="space-y-2 pt-2">
            <div className="flex items-center justify-between text-xs text-slate-700 font-medium">
              <span>Previewing <strong className="text-blue-600">{parsedDrivers.length}</strong> driver records to be synchronized:</span>
            </div>
            <div className="overflow-x-auto max-h-60 rounded-xl border border-slate-200">
              <table className="w-full text-left text-xs text-slate-700">
                <thead className="bg-slate-50 text-slate-500 text-[10px] uppercase font-bold border-b border-slate-200">
                  <tr>
                    <th className="px-3 py-2">Employee ID</th>
                    <th className="px-3 py-2">Login ID</th>
                    <th className="px-3 py-2">Name</th>
                    <th className="px-3 py-2">Depot</th>
                    <th className="px-3 py-2">Designation</th>
                    <th className="px-3 py-2">License</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 bg-white text-[11px]">
                  {parsedDrivers.slice(0, 15).map((d, idx) => (
                    <tr key={idx} className="hover:bg-slate-50">
                      <td className="px-3 py-1.5 font-mono font-bold text-slate-900">{d.employeeId}</td>
                      <td className="px-3 py-1.5 font-mono text-slate-700">{d.loginId}</td>
                      <td className="px-3 py-1.5 font-semibold text-slate-900">{d.name}</td>
                      <td className="px-3 py-1.5 font-mono">
                        <span className="bg-slate-100 px-1.5 py-0.5 rounded font-bold text-slate-700 text-[10px]">
                          {d.depot}
                        </span>
                      </td>
                      <td className="px-3 py-1.5 text-slate-700">{d.designation}</td>
                      <td className="px-3 py-1.5 text-slate-500">{d.licenseType}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Commit Action */}
        <div className="flex items-center justify-end pt-3 border-t border-slate-100">
          <button
            type="button"
            disabled={
              isProcessing ||
              (activeType === 'vehicles' ? parsedVehicles.length === 0 : parsedDrivers.length === 0)
            }
            onClick={handleCommit}
            className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-6 py-2.5 rounded-xl text-xs flex items-center space-x-2 shadow-md shadow-blue-500/25 disabled:opacity-50 transition cursor-pointer"
          >
            {isProcessing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4" />}
            <span>
              {activeType === 'vehicles' ? 'Upload & Auto-Generate QR Codes' : 'Upload & Sync Drivers'}
            </span>
          </button>
        </div>
      </div>

      {/* Wipe Confirmation Modal */}
      {showWipeModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl p-6 sm:p-7 max-w-md w-full shadow-2xl border border-slate-200 text-slate-800 space-y-5 animate-in fade-in zoom-in duration-150">
            <div className="flex items-start justify-between">
              <div className="w-12 h-12 rounded-2xl bg-rose-50 border border-rose-100 flex items-center justify-center text-rose-600 flex-shrink-0">
                <Trash2 className="w-6 h-6" />
              </div>
              <button
                type="button"
                onClick={() => setShowWipeModal(false)}
                className="p-1.5 text-slate-400 hover:text-slate-600 rounded-lg"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-2">
              <h3 className="text-base font-bold text-slate-900">
                Wipe Fleet Database
              </h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Choose which dataset to clear. This permanently removes records from storage so you can re-upload your own data from a clean state.
              </p>
            </div>

            {/* Scope Selection */}
            <div className="space-y-2 text-xs">
              <label className="flex items-center space-x-3 p-3 rounded-xl border border-slate-200 cursor-pointer hover:bg-slate-50">
                <input
                  type="radio"
                  name="wipeScope"
                  checked={wipeMode === 'all'}
                  onChange={() => setWipeMode('all')}
                  className="text-rose-600 focus:ring-rose-500"
                />
                <div>
                  <div className="font-bold text-slate-900">Wipe Everything (100% Clean Slate)</div>
                  <div className="text-[11px] text-slate-500">Deletes all vehicles, drivers, inspections, and audit logs.</div>
                </div>
              </label>

              <label className="flex items-center space-x-3 p-3 rounded-xl border border-slate-200 cursor-pointer hover:bg-slate-50">
                <input
                  type="radio"
                  name="wipeScope"
                  checked={wipeMode === 'vehicles'}
                  onChange={() => setWipeMode('vehicles')}
                  className="text-rose-600 focus:ring-rose-500"
                />
                <div>
                  <div className="font-bold text-slate-900">Clear Vehicles Only</div>
                  <div className="text-[11px] text-slate-500">Clears registered vehicles and associated inspections.</div>
                </div>
              </label>

              <label className="flex items-center space-x-3 p-3 rounded-xl border border-slate-200 cursor-pointer hover:bg-slate-50">
                <input
                  type="radio"
                  name="wipeScope"
                  checked={wipeMode === 'drivers'}
                  onChange={() => setWipeMode('drivers')}
                  className="text-rose-600 focus:ring-rose-500"
                />
                <div>
                  <div className="font-bold text-slate-900">Clear Drivers Only</div>
                  <div className="text-[11px] text-slate-500">Clears driver login profiles and credentials.</div>
                </div>
              </label>
            </div>

            <div className="flex items-center justify-end space-x-3 pt-2">
              <button
                type="button"
                onClick={() => setShowWipeModal(false)}
                className="px-4 py-2.5 rounded-xl border border-slate-200 text-xs font-semibold text-slate-600 hover:bg-slate-50 transition cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="button"
                disabled={isProcessing}
                onClick={handleExecuteWipe}
                className="px-5 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold shadow-md shadow-rose-600/30 flex items-center space-x-2 transition cursor-pointer disabled:opacity-50"
              >
                {isProcessing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
                <span>Confirm & Wipe</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
